# Generated by Django 4.1.2 on 2022-11-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(db_table='movie_genres', to='movies.genre'),
        ),
    ]
