# Generated by Django 4.1.2 on 2022-11-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movie_genres', to='movies.genre'),
        ),
    ]
